---
functional:
  - Пользователь должен иметь возможность выбирать язык программирования
  - Пользователь должен имень возможность выбрать игру по уровню сложности
  - Поддержка всех популярных языков программирования
  - Возможность Участника выбрать тип игры - с другим пользователем, с другом по ссылке, с ботом
  - Ведение рейтинга зарегистрированных пользователей 
  - Возможность отображения редакторов кода 
  - Возможность авторизации через Github
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Возможность создавать отдельный чат для каждой игры
  - Пользователь не может вносить изменения в таблицу лидеров вручную
  - Пользователь не может писать и изменять код соперника
