---
functional:
  - Пользователь должен иметь возможность выбирать язык программирования
  - Пользователь должен имень возможность выбрать игру по уровню сложности
  - Поддержка всех популярных языков программирования
  - Возможность Участника выбрать тип игры - с другим пользователем, с другом по ссылке, с ботом
  - Ведение рейтинга зарегистрированных пользователей 
  - Возможность отображения редакторов кода 
  - Возможность авторизации через Github
  - Возможность зарегистрироваться с помощью e-mail
  - Возможность пользователю без регистрации подключиться к простой случайной игре с ботом
  - Возможность участникам отправлять сообщения в общий чат
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Сайт должен поддерживать несколько языков
  - Пользователь не может писать и изменять код соперника
