---
functional:
  - Пользователь должен иметь возможность выбирать язык программирования
  - Пользователь должен имень возможность выбрать игру по уровню сложности
  - Поддержка всех популярных языков программирования
  - Возможность Участника выбрать тип игры - с другим пользователем, с другом по ссылке, с ботом
  - Ведение рейтинга зарегистрированных пользователей 
  - Возможность отображения редакторов кода 
  - Возможность авторизации через Github
  - Возможность зарегистрироваться с помощью e-mail
  - Возможность пользователю без регистрации подключиться к простой случайной игре с ботом
  - Возможность участникам отправлять сообщения в общий чат
  - Пользователь должен иметь возможность авторизоваться для входа в приложение
  - Игра завершается при победе, самостоятельной сдаче, победе противника, сдаче противника, завершении времени
  - При выходе обоих игроков, игра считается полностью законченной и удаляется из памяти
  - Пользователь может переподключится к игре в случае если игра вылетела
  - После победы одного из игроков, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры
  - Решение задачи на скорость против другого игрока
  - Задачи для решения даны на двух языках — русском и английском
  - Каждый игрок видит код своего соперника в режиме онлайн
  - Каждый игрок имеет кнопку "check" для проверки своего решения
  - Количество попыток проверки должно быть неограниченно
  - Пользователь должен иметь возможность создать игру
  - После определения победителя должна быть возможность остаться в баттле и ознакомиться с кодом
  - Должно приходить уведомление о начале баттла
  - При создании игры с другим пользователем, пользователь находится в режиме ожидания второго игрока
  - При создании игры с другим пользователем игра высвечивается как "доступная для подключения" у других пользователей
  - Во время матча на экране отображается задание и время игры
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Сайт должен поддерживать несколько языков
  - Пользователь не может писать и изменять код соперника
  - Пользователь может восстановить пароль от аккаунта 
  - Пользователь может выйти из аккаунта
